'\"
'\" Copyright 1989 Regents of the University of California
'\" Permission to use, copy, modify, and distribute this
'\" documentation for any purpose and without fee is hereby
'\" granted, provided that this notice appears in all copies.
'\" The University of California makes no representations about
'\" the suitability of this material for any purpose.  It is
'\" provided "as is" without express or implied warranty.
'\" 
'\" $Header: /user6/ouster/tcl/man/RCS/StrMatch.3,v 1.5 93/01/31 15:35:41 ouster Exp $ SPRITE (Berkeley)
'\" 
.so man.macros
.HS Hax_StringMatch hax
.BS
.SH NAME
Hax_StringMatch \- test whether a string matches a pattern
.SH SYNOPSIS
.nf
\fB#include <hax.h>\fR
.sp
int
\fBHax_StringMatch\fR(\fIstring\fR, \fIpattern\fR)
.SH ARGUMENTS
.AP char *string in
String to test.
.AP char *pattern in
Pattern to match against string.  May contain special
characters from the set *?\e[].
.BE

.SH DESCRIPTION
.PP
This utility procedure determines whether a string matches
a given pattern.  If it does, then \fBHax_StringMatch\fR returns
1.  Otherwise \fBHax_StringMatch\fR returns 0.  The algorithm
used for matching is the same algorithm used in the ``string match''
Hax command and is similar to the algorithm used by the C-shell
for file name matching;  see the Hax manual entry for details.

.SH KEYWORDS
match, pattern, string
